#!/bin/bash
# inpath--특정프로그램 유효한지 확인
in_path(){
  cmd=$1  
  ourpath=$2  
  result=1
  oldIFS=$IFS 
  IFS=":"
  
  for directory in $ourpath
  do
    if [ -x $directory/$cmd ] ; then
      result=0 # 명령어 발견시
    fi
  done

  IFS=$oldIFS
  return $result
}

# checkForCmdInPath : PATH 디렉터리 목록에서 찾을 수 있는지 확인
checkForCmdInPath(){
  var=$1
  if [ "$var" != "" ] ; then
    if [ "${var:0:1}" = "/" ] ; then
      if [ ! -x $var ] ; then
        return 1
      fi
    elif ! in_path $var "$PATH" ; then
      return 2
    fi
  fi
}

# 결과
if [ $# -ne 1 ] ; then
  echo "Usage: $0 command" >&2
  exit 1
fi

checkForCmdInPath "$1"
case $? in
  0 ) echo "$1 found in PATH" ;;
  1 ) echo "$1 not found or not excutable" ;;
  2 ) echo "$1 not found in PATH" ;;
esac

exit 0
  